# Generated by Django 5.2.6 on 2025-09-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0003_pet_adopted_pet_approved_alter_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email where adopters can contact the owner', max_length=254, null=True),
        ),
    ]
